### ISSUE TITLE
Google clickjack; re-ofuscating links on click

### ISSUE THREAD

**Issue by mikewaters** [dividedby/General-URL-Cleaner-Revived#10]
This userscript nicely cleans the Google SERP links, de-obfuscating them and hence removing the click tracking - I've validated this in the debugger.
However, on click/right-click Google re-obfuscates the damn URL, which renders this protection ineffective. Listening to `DOMSubtreeModified`, you can watch it happen.
After doing some research, apparently it has been this way for some time, and there are some ways to mitigate it - like reverting the DOM mutation. There is also a paid Safari/Mac solution, the app [Stop the Madness](https://underpassapp.com/StopTheMadness/) (I am in no way related to them) but I haven't tried it.

Thanks for the code, it works great for more than just The Borg so I'll continue to use it!

A gif:
![Screen recording of right-click](https://github.com/dividedby/General-URL-Cleaner-Revived/assets/149978/98491221-2438-4533-b687-8d1c25ac67b7)

**Comment by dividedby** [comment]
> This userscript nicely cleans the Google SERP links, de-obfuscating them and hence removing the click tracking - I've validated this in the debugger. However, on click/right-click Google re-obfuscates the damn URL, which renders this protection ineffective. Listening to `DOMSubtreeModified`, you can watch it happen. After doing some research, apparently it has been this way for some time, and there are some ways to mitigate it - like reverting the DOM mutation. There is also a paid Safari/Mac solution, the app [Stop the Madness](https://underpassapp.com/StopTheMadness/) (I am in no way related to them) but I haven't tried it.
> 
> Thanks for the code, it works great for more than just The Borg so I'll continue to use it!

Thanks for the report and glad you are liking the script! Unfortunately I think something like that is outside of my scope knowledge currently and I don't have much time to work on the script. Maybe in the future it is something I try and look in to.

**Comment by mikewaters** [comment]
Thank you, I will close the issue; even if you *do* fix it, one of thousands of engineers will un-fix it shortly :). I've installed the `StopTheMadness` extension because frankly its driving me mad! :). 

Be well.

**Comment by mikewaters** [comment]
whoops
