### ISSUE TITLE
Please add support for DuckDuckGo

### ISSUE THREAD

**Issue by Spork-Schivago** [dividedby/General-URL-Cleaner-Revived#11]
I just installed this script but havent had a chance to test it.    I am hoping it works the way I am thinking.    If so, I would like to see support for DuckDuckGo.

I will give an example.   I search for Google Chromecast for sale and then I click on the shopping tab.    I click the first item, which is from Verizon, and this is the url it tries to take me to:

https://8627.xg4ken.com/trk/v1?prof=409&camp=15155&kct=msn&kchid=149494633&criteriaid=pla-4580359297875765&campaignid=675584062&locphy=&adgroupid=1228155499333123&cid=76759849642364&kdv=m&kext=&kpg=4580359297875765&kpid=GA03131-US&queryStr=Google%20Chromecast%20for%20sale&url=https://www.verizon.com/products/google-chromecast-google-tv-hd?sku=sku5580297&cmp=CSE_M_X_COE_GAW_ACCESS_2023_11_PLA-15155&kpid=bi_cmp-675584062_adg-1228155499333123_ad-76759849642364_pla-4580359297875765_dev-m_ext-{extensionid}_sig-3cc6498dd338180c90452cf8291997b6&msclkid=3cc6498dd338180c90452cf8291997b6

I would like it where it would just try taking me to:

https://www.verizon.com/products/google-chromecast-google-tv-hd

This this possible?   Thank you.

**Comment by dividedby** [comment]
> I just installed this script but havent had a chance to test it. I am hoping it works the way I am thinking. If so, I would like to see support for DuckDuckGo.
> 
> I will give an example. I search for Google Chromecast for sale and then I click on the shopping tab. I click the first item, which is from Verizon, and this is the url it tries to take me to:
> 
> [https://8627.xg4ken.com/trk/v1?prof=409&camp=15155&kct=msn&kchid=149494633&criteriaid=pla-4580359297875765&campaignid=675584062&locphy=&adgroupid=1228155499333123&cid=76759849642364&kdv=m&kext=&kpg=4580359297875765&kpid=GA03131-US&queryStr=Google%20Chromecast%20for%20sale&url=https://www.verizon.com/products/google-chromecast-google-tv-hd?sku=sku5580297&cmp=CSE_M_X_COE_GAW_ACCESS_2023_11_PLA-15155&kpid=bi_cmp-675584062_adg-1228155499333123_ad-76759849642364_pla-4580359297875765_dev-m_ext-{extensionid}_sig-3cc6498dd338180c90452cf8291997b6&msclkid=3cc6498dd338180c90452cf8291997b6](https://8627.xg4ken.com/trk/v1?prof=409&camp=15155&kct=msn&kchid=149494633&criteriaid=pla-4580359297875765&campaignid=675584062&locphy=&adgroupid=1228155499333123&cid=76759849642364&kdv=m&kext=&kpg=4580359297875765&kpid=GA03131-US&queryStr=Google%20Chromecast%20for%20sale&url=https://www.verizon.com/products/google-chromecast-google-tv-hd?sku=sku5580297&cmp=CSE_M_X_COE_GAW_ACCESS_2023_11_PLA-15155&kpid=bi_cmp-675584062_adg-1228155499333123_ad-76759849642364_pla-4580359297875765_dev-m_ext-%7Bextensionid%7D_sig-3cc6498dd338180c90452cf8291997b6&msclkid=3cc6498dd338180c90452cf8291997b6)
> 
> I would like it where it would just try taking me to:
> 
> https://www.verizon.com/products/google-chromecast-google-tv-hd
> 
> This this possible? Thank you.

Basically I would need to add support for verizon.com, if I have time I will see about adding it to the script, just not sure if it will be a priority right now.

**Comment by dividedby** [comment]
Not planning support for Verizon at this time
