### ISSUE TITLE
Amazon URLs stripped

### ISSUE THREAD

**Issue by arogl** [dividedby/General-URL-Cleaner-Revived#14]
Browser: Windows 64 Version 121.0.6167.161 (Official Build) (64-bit)
Tampermonkey: 5.1.6193
Script version: 4.1.9 Installed from GreasyFork

The following URL is stripped to become just the Amazon homepage

```
https://www.amazon.com/s/ref=dbs_m_mng_rwt_byln?_encoding=UTF8&field-author=Steven++Masters&search-alias=digital-text
```

```
https://www.amazon.com/
```

Without the script enabled, this becomes

```
https://www.amazon.com/s?i=digital-text&rh=p_27%3ASteven+Masters&_encoding=UTF8&ref=dbs_m_mng_rwt_byln
```

**Comment by dividedby** [comment]
For me, the URL you shared is cleaned to:

~~~
https://www.amazon.com/s/?field-author=Steven++Masters&search-alias=digital-text
~~~

Which Amazon changes into the below:

~~~
https://www.amazon.com/s?i=digital-text&rh=p_27%3ASteven++Masters
~~~

If you notice any other issues, please let me know!
