### ISSUE TITLE
I hope this script will remove the tracking from the "copy tweet link"

### ISSUE THREAD

**Issue by Alphabet1226** [dividedby/General-URL-Cleaner-Revived#2]
Whether in tweets or comments, links copied through here come with a tracking parameter, for example: https://twitter.com/github/status/1425505817827151872

**Comment by dividedby** [comment]
Hello, sorry for taking so long to respond, however I don't think there is any way that I can change the URL that is copied from that button. It is generated by an API call to Twitter's backend and saved to the clipboard. If you copy the URL and then enter it in another tab it will remove the tracking parameters.
