### ISSUE TITLE
[Request] Links from https://isthereanydeal.com/

### ISSUE THREAD

**Issue by TFWol** [dividedby/General-URL-Cleaner-Revived#3]
Any thoughts on looking at some of the redirects like on [this page](https://isthereanydeal.com/#/page:game/info?plain=eldenring)?

Referral codes are fine and dandy, but 3rd party redirects are a big nope.
Hover over the Fanatical and Newegg links for some of the worst offenders.
![image](https://user-images.githubusercontent.com/9045213/200089116-766f11ac-a54e-465f-8766-ed61355f102c.png)

Regex eludes me else I'd be making a pull request.

**Comment by dividedby** [comment]
I would recommend checking out the Skip Redirects extension, as I believe that is what you're looking for: https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/  

Skipping third party redirects is out of the scope of this script
