### ISSUE TITLE
Parameter 'sclient'

### ISSUE THREAD

**Issue by realAzazello** [dividedby/General-URL-Cleaner-Revived#4]
Perhaps more questions than request... I can't find a definitive answer on what 'sclient' is actually doing in g-search links -- and based on both manually removing it, and using addons like ClearURL, 'AdGuard URL Tracking Protection', etc, it seems to not negatively affect anything (except Google's tracking).

So... should it be added to the script?

**Comment by dividedby** [comment]
@realAzazello the script should be removing the sclient param now, let me know if not or you find any other params that can be safely removed! If you do, just open a new issue and I'll work on it as soon as I can.
