### ISSUE TITLE
Prevent 'undefined' at end of cleaned URLs

### ISSUE THREAD

**Issue by zkisaboss** [dividedby/General-URL-Cleaner-Revived#5]
I would love to see support for Etsy, but there's another problem with URLs. After cleaning them, 'undefined' gets added to the end, which can cause issues, especially with Google Docs, where the URL won't fully load and keeps adding 'undefined' at the end.

**Comment by dividedby** [comment]
@zkisaboss undefined shouldn't be added to the end of URLs anymore, but please let me know if you still see that happen anywhere. Also, if you could provide me with some examples of "dirty" Etsy URLs and their working "clean" versions? Then I should be able to work on adding Etsy support. You can open a new issue for that.
