### ISSUE TITLE
Etsy Support

### ISSUE THREAD

**Issue by zkisaboss** [dividedby/General-URL-Cleaner-Revived#7]
Here are the examples you requested. This is the same link in three different ways.

https://www.etsy.com/listing/1035684640/personalised-song-plaque-with-stand-any?click_key=f3ca5032133bcd335796a43b48753168ca8472dc%3A1035684640&click_sum=8e055e5b&ref=shop_home_feat_1&pro=1&frs=1

https://www.etsy.com/listing/1035684640/personalised-song-plaque-with-stand-any?pro=1&frs=1 

https://www.etsy.com/listing/1035684640/personalised-song-plaque-with-stand-any

**Comment by zkisaboss** [comment]
Another example with more parameters.

https://www.etsy.com/listing/1419460358/crochet-daisy-plant-crochet-plant-car?ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=cute+things&ref=sr_gallery-1-2&pro=1&sts=1&organic_search_click=1

https://www.etsy.com/listing/1419460358/crochet-daisy-plant-crochet-plant-car?ga_search_query=cute+things&pro=1&sts=1&organic_search_click=1 

https://www.etsy.com/listing/1419460358/crochet-daisy-plant-crochet-plant-car

**Comment by dividedby** [comment]
Thanks for those, I'll probably be able to implement support tomorrow or at least a first go.

**Comment by dividedby** [comment]
Just added initial Etsy support, give it a go and let me know if you run into any issues. For whatever reason it seems to take a couple of reloads to get down to a fully cleaned link and even then it leaves a trailing "?" but I will keep trying to look into it and make improvements.

**Comment by zkisaboss** [comment]
Thanks for the quick rollout!
