### ISSUE TITLE
Breaks Amazon Pages

### ISSUE THREAD

**Issue by UPSKingpin** [dividedby/General-URL-Cleaner-Revived#9]
Seems to break a ton of Amazon pages. When browsing the home page or category pages, clicking a selection results in a "Page not found" for hundreds of links. Seems they changed some URL formatting at some point, because there was no issue with the extension for a long time.

**Comment by dividedby** [comment]
> Seems to break a ton of Amazon pages. When browsing the home page or category pages, clicking a selection results in a "Page not found" for hundreds of links. Seems they changed some URL formatting at some point, because there was no issue with the extension for a long time.

Thanks for the report. Would you be able to provide some example links and what the new good, clean links should be? I haven't had much time to actively maintain this script so any help would be appreciated.

**Comment by UPSKingpin** [comment]
Absolutely, glad to help.

Currently on the home page, there's an option "Shop branded gift cards" in the featured area. Clicking it with the script enabled sends me to the following page:
`https://www.amazon.com/b?node=14485264011&pf_rd_r=B6ESEAEACQ9Q2K58ARN6&pf_rd_p=037aa4b6-2ea7-4596-af82-19108a56134b&pd_rd_r=3cd6c3cd-5cc9-4a5c-a100-e40b24a185be&pd_rd_w=BGMk7&pd_rd_wg=FasaQ&ref_=pd_gw_unk`

When I turn off the script and reload the home page, then try again, I am directed to this page:
`https://www.amazon.com/b?node=14485264011&ref=US_T5_23_BFCM_GW_AdTopper_EN&pd_rd_w=dGIVy&content-id=amzn1.sym.037aa4b6-2ea7-4596-af82-19108a56134b&pf_rd_p=037aa4b6-2ea7-4596-af82-19108a56134b&pf_rd_r=JB82YFMTK9770RGCXX2C&pd_rd_wg=z3U5A&pd_rd_r=b4d6831c-42a9-4c52-ab42-c8f5fa2e1f03`

Does that help? Let me know if you'd like some more examples. Basically, if you start browsing by category instead of just searching, you'll end up with the same issue clicking through categories.

**Comment by dividedby** [comment]
> Does that help? Let me know if you'd like some more examples. Basically, if you start browsing by category instead of just searching, you'll end up with the same issue clicking through categories.

Does the issue still occur for you? I can't seem to be able to replicate it. I am testing in a clean Firefox profile with no extensions running other than this script.

**Comment by UPSKingpin** [comment]
It is, unfortunately. I'm running Chrome and just tried it in a bare incognito window with only this script running. I manually navigated to All > Clothing > Men, which brought me here: https://www.amazon.com/gp/browse.html?node=7147441011

But when I click on Shoes or any other option at the top of that page, I get a "Sorry, we couldn't find that page" at https://www.amazon.com/b/ref=hol23_ml1_mob_nav_fgg_3?pf_rd_p=4ece5337-87a0-4792-abc8-66f6523e2a3apf_rd_s=merchandised-search-3pf_rd_i=7147441011node=679255011

**Comment by dividedby** [comment]
> It is, unfortunately. I'm running Chrome and just tried it in a bare incognito window with only this script running. I manually navigated to All > Clothing > Men, which brought me here: https://www.amazon.com/gp/browse.html?node=7147441011
> 
> But when I click on Shoes or any other option at the top of that page, I get a "Sorry, we couldn't find that page" at https://www.amazon.com/b/ref=hol23_ml1_mob_nav_fgg_3?pf_rd_p=4ece5337-87a0-4792-abc8-66f6523e2a3apf_rd_s=merchandised-search-3pf_rd_i=7147441011node=679255011

That helped, thanks! I just published an update that I think should fix the issue.

**Comment by UPSKingpin** [comment]
Excellent! Just installed it and it looks like everything is working beautifully. Thanks for being so responsive!
